server.port=8080

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

jwt.secret=minha-chave-segredo-super-secreta
jwt.expiration=3600000

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost/blog?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSL=false
spring.datasource.username=root
spring.datasource.password=

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Sao_Paulo

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.packagesToScan=blog.controller

# Para deploy futuramente
#spring.datasource.url=${JDBC_DATASOURCE_URL}

# Compressão HTTP
#server.compression.enabled=true
#server.compression.min-response-size=1024
